### ISSUE TITLE
Using KV instead of R2

### ISSUE THREAD

**Issue by Saiv46** [gfodor/p2pcf#4]
I can't get it. Why would you use R2 while it's in beta and have stricter limits than KV. It's also a overkill for storing a bunch of JSON

**Comment by gfodor** [comment]
I built this first using KV, but it doesn’t work because of eventual consistency. The delays for the writes to propagate can be up to 10s, so negotiations can take 30s or more, resulting in ICE timeouts and a poor user experience.

**Comment by Saiv46** [comment]
Didn't R2 have same problem? As I know, that storage is distributed too.

For consistency - Durable Objects is intended, with timeout of 30s its enough to be used without any storage

**Comment by gfodor** [comment]
No, R2 doesn’t have this problem. It is strongly consistent storage with
global read after write semantics.

**Comment by gfodor** [comment]
Re: durable objects I’d be interested in an analysis that showed it would
be cheaper. As it is, R2 works great and is very cheap.

**Comment by zalo** [comment]
Light Analysis:
Since Durable Objects now have [hibernatable connections](https://developers.cloudflare.com/durable-objects/best-practices/websockets/#websocket-hibernation-api) (which allows the worker to shut down and restart as needed while keeping the websocket connection open), it might be possible to store/compute the signaling state within the hibernating websocket connections without need for R2 or KV...

Though, even if you couldn't, it seems like both R2 and KV get 1 million read/write/deletes per month, so the point is moot until you're big enough to pay for it yourself...
